# Generated by Django 2.2.7 on 2019-11-15 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_showingroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(10, 'Active'), (20, 'Past'), (30, 'Sold Out')], default=10)),
                ('name', models.CharField(max_length=100)),
                ('price_per_ticket', models.DecimalField(decimal_places=2, max_digits=6)),
                ('remaining_seats', models.PositiveIntegerField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Movie')),
                ('showing_room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tickets.ShowingRoom')),
            ],
        ),
    ]
