# Generated by Django 2.2.7 on 2019-11-15 18:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_showing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('showing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.Showing')),
            ],
        ),
    ]
